:schedule:
  fetch_pos_job:
    cron: "*/1 * * * *"
    class: "FetchPosJob"
    queue: "default"
  fetch_printers_job:
    cron: "*/1 * * * *"
    class: "FetchPrintersJob"
    queue: "default"
  fetch_red_systems_job:
    cron: "*/1 * * * *"
    class: "FetchRedSystemsJob"
    queue: "default"